config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :study_items, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/study_item.rb
class StudyItem < ApplicationRecord
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @study_items = StudyItem.all
  end
end

app/controllers/study_items_controller.rb
class StudyItemsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]

  def new
  end

  def create
    StudyItem.create(params.require(:study_item).permit(:title, :description, :done))
    redirect_to root_path
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyGuide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br><br><br>
    <nav>
    <% if user_signed_in? %>
      <span><%= current_user.email %></span>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
Boas-vindas ao Guia de Estudos


<p>É hora de estudar</p>

<h2>Lista de Estudos:</h2>
<% @study_items.each do |study_item| %>
  <%= study_item.title %>
<% end %>

<%= link_to 'Cadastrar item', new_study_item_path %>

app/views/study_items/new.html.erb
<h1>Cadastrar novo item</h1>

<%= form_with(model: StudyItem.new) do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, 'Descrição' %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.check_box :done %>
    <%= f.label :done, 'Feito' %>
  </div>
  <%= f.submit 'Salvar' %>
<% end %>